---
include:
  - project: 'bmhughes-net-chef/bmhughes_net_chef_testing'
    ref: master
    file: 'gitlab-ci-chef-cookbook.yml'

kitchen_test:
  parallel:
    matrix:
      - SUITE: default
        PLATFORM: [centos-7, centos-stream-8, fedora-34, debian-10, ubuntu-1804, ubuntu-2004]
...
