name 'net_snmp_test'
maintainer 'Ben Hughes'
maintainer_email 'bmhughes@bmhughes.co.uk'
license 'Apache-2.0'
description 'net_snmp test cookbook'
version '0.1.0'
chef_version '>= 16.0'
depends 'net_snmp'
